PPF/Models/ViewModels/PickViewModel.cs
using System.Collections.Generic;

namespace PPF.Models.ViewModels
{
    public class PickViewModel
    {
        public int Id { get; set; }
        public GameViewModel Game { get; set; }
        public int PointTotal { get; set; }
        public string UserId { get; set; }
        public TeamViewModel Team { get; set; }
        public bool IsStandard { get; set; }
        public bool IsWinner { get; set; }
        public List<int> PossiblePoints { get; set; }
    }
}

PPF/Models/ViewModels/SuperbowlPlayoffPickerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PPF.Models.ViewModels
{
    public class SuperbowlPlayoffPickerViewModel
    {
        public List<SuperbowlPlayoffPickViewModel> Picks { get; set; }
        public List<TeamViewModel> Teams { get; set; }
    }
}

PPF/Controllers/MyPredictController.cs
using System.Collections.Generic;
using System.Data.Objects;
using System.Web.Mvc;
using PPF.Models;
using PPF.Models.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;

namespace PPF.Controllers
{
    public class MyPredictController : Controller
    {
        private readonly SeasonService _svc;

        public MyPredictController()
        {
            _svc = new SeasonService();
        }
    
        [Authorize]
        public ActionResult Index()
        {
            return View(_svc.GetCurrentSeason(User.Identity.Name));
        }

        [Authorize]
        public ActionResult Tab(int week)
        {
            var vm = _svc.SetupWeek(week, User.Identity.Name);
            return View(vm);
        }

        [Authorize]
        public JsonResult GetWeeklyLeaderboard(int week)
        {
            var vm = _svc.GetWeeklyLeaderboard(week);
            return Json(vm);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AcceptPicks(MyPredictViewModel vm, FormCollection formValues)
        {
            var pPicks = (from formValue in formValues.AllKeys
                           where formValue.Contains("_team_playoff_") && bool.Parse(Request.Form.GetValues(formValue)[0])
                           let idx = formValue.LastIndexOf("_")
                           select new TeamViewModel() {Id = int.Parse(formValue.Substring(idx + 1, formValue.Length - (idx + 1)))}
                           into team select new SuperbowlPlayoffPickViewModel() { IsPlayoff = true, Team = team, UserId = User.Identity.Name }).ToList();

            var sPicks = (from formValue in formValues.AllKeys
                          where formValue.Contains("_team_superbowl_") && bool.Parse(Request.Form.GetValues(formValue)[0])
                            let idx = formValue.LastIndexOf("_")
                            select new TeamViewModel() { Id = int.Parse(formValue.Substring(idx + 1, formValue.Length - (idx + 1))) }
                            into team
                            select new SuperbowlPlayoffPickViewModel() { IsPlayoff = true, Team = team, UserId = User.Identity.Name}).ToList();


            vm.MyPlayoffPicks = pPicks;
            vm.MySuperbowlPicks = sPicks;

            if (vm.AreStandardPicks)
                _svc.SaveStandardPicks(vm, User.Identity.Name);
            else
            {
                _svc.SavePick(vm, User.Identity.Name);
                if (User.IsInRole("Admins"))
                    _svc.UpdateWeeklyScores(vm);
            }


            return Json("success");

        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult CalcPsPicks()
        {
            _svc.CalcSuperbowlPlayoffPicks(null);
            return Json("success");
        }


        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult SaveGame(string gameId, string gameDateTime)
        {
            var gvm = new GameViewModel() {Id = int.Parse(gameId), GameDateTime = DateTime.Parse(gameDateTime)};
            _svc.SaveGame(gvm, User.Identity.Name);
            return Json("success");
        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult DeleteGame(string gameId)
        {
            try
            {
                var gid = int.Parse(gameId);
                _svc.DeleteGame(gid);
                return Json("success");
            }
            catch (Exception ex)
            {
                return Json(ex.ToString());
            }
        }

        
        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult SaveSeason(string startDate, string weeks, int id, int dId)
        {
            var ssD = DateTime.Parse(startDate);
            var sWe = int.Parse(weeks);
            _svc.SaveSeason(id, sWe, ssD, dId);
            return Json("success");
        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult AddGame(int homeTeamId, int awayTeamId, string gameDateTime, string gameType, int week)
        {
            var isPlayoff = false;
            var isSuperbowl = false;
            if (gameType.ToUpper().Equals("P"))
                isPlayoff = true;
            else if (gameType.ToUpper().Equals("S"))
                isSuperbowl = true;
            //
            var gDt = DateTime.Parse(gameDateTime);
            var team = _svc.AddGame(homeTeamId, awayTeamId, gDt, isPlayoff, isSuperbowl, week);
            return Json(team);
        }

        [Authorize(Roles = "Admins")]
        [HttpPost]
        public JsonResult SearchSeason(string term)
        {
            return Json(_svc.SearchSeasons(term));
        }

        [Authorize(Roles="Admins")]
        [HttpPost]
        public JsonResult SearchTeams(string term)
        {
            return Json(_svc.SearchTeams(term));
        }

        [Authorize(Roles="Admins")]
        [HttpPost]
        public JsonResult GetCurrentSeason()
        {
            return Json(_svc.GetCurrentSeason());

        }
    }
}

PPF/Views/Shared/PickTable.cshtml
@model IList<PPF.Models.ViewModels.PickViewModel>

PPF/Views/Shared/SuperbowlPlayoffPicker.cshtml
@model PPF.Models.ViewModels.SuperbowlPlayoffPickerViewModel
<div style="width: 49%; float: right;">
    <h2>
        NFC Teams</h2>
    
</div>
<div style="width: 50%;">
    <h2>
        AFC Teams</h2>
    <table cellpadding="0" cellspacing="0" class="picker">
        <thead>
            <tr>
                <th class="ui-widget ui-widget-header">
                    Team
                </th>
                <th class="ui-widget ui-widget-header">
                    Playoff Pick?
                </th>
                <th class="ui-widget ui-widget-header">
                    Superbowl Pick
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var team in Model.Teams.Where(t => t.Conference.ToUpper() == "AFC"))
            {
                <tr>
                    <td>@team.TeamName
                    </td>
                    <td>@Html.CheckBox(string.Concat(team.Conference, "_team_playoff_", team.Id), Model.Picks.Where(p => p.IsPlayoff && p.Team.Id.Equals(team.Id)).Count().Equals(1))
                    </td>
                    <td>@Html.CheckBox(string.Concat(team.Conference, "_team_superbowl_", team.Id), Model.Picks.Where(p => p.IsSuperbowl && p.Team.Id.Equals(team.Id)).Count().Equals(1))
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PPF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.11/themes/black-tie/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/PPF.css")" rel="stylesheet" type="text/css" />

    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.5.2.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.11/jquery-ui.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8/jquery.validate-vsdoc.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.validate.unobtrusive.js" type="text/javascript"></script>
    <script src=""@Url.Content("~/Scripts/jquery.qtip.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.equalheights.js")" type="text/javascript"></script>
</head>
<body>
    <div id="hd">
        <div class="logo">
        </div>
        <div class="login">
            <input type="button" id="btnMember" value="Sign Up" />
            <input type="button" id="btnLogin" value="Login" />
        </div>
    </div>
    <div id="container">
        <div id="center">
            <div style="padding: 1em;" class="content">@RenderBody()</div>
        </div>
        <div id="leftRail">
            <div style="padding: 1em; border-right: 1px solid #ccc;" class="content">
                <ul id="main-nav">
                    <li><a href="#"><span class="icon home"></span><span class="main-nav-label">Home</span></a></li>
                    <li><a href="#"><span class="icon profile"></span><span class="main-nav-label">My Profile</span></a></li>
                    <li><a href="#"><span class="icon notepad"></span><span class="main-nav-label">How to
                        Pick</span></a></li>
                    <li><a href="#"><span class="icon notepad"></span><span class="main-nav-label">Standard
                        Picks</span></a></li>
                    <li><a href="#"><span class="icon question"></span><span class="main-nav-label">About</span></a></li>
                </ul>
                <div class="divider">
                </div>
            </div>
        </div>
        <div id="rightRail">
            <div style="padding: 1em; color: #fff;" class="content">
                Right Sidebar</div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".content").equalHeights();
            $("input[type='button']").button();
        });
    </script>
</body>
</html>

PPF/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text><span style="color: #fff">Welcome <b>@Context.User.Identity.Name</b>!</span>&nbsp;
    <input type="button" value="Log Off" id="btnLogOff" />
    </text>
}
else {
    <text><input type="button" value="Log On" id="btnLogOn" />&nbsp;
          <input type="button" value="Register" id="btnRegister" />
    </text>
}

<script type="text/javascript">

    $(function () {

        $("#btnLogOff").click(function () {

            window.location = '@Url.Action("LogOff", "Home")';

        });

        $("#btnLogOn").click(function () {

            window.location = '@Url.Action("Index", "Home")';

        });

        $("#btnRegister").click(function () {

            window.location = '@Url.Action("Register", "Home")';

        });



    });

</script>

PPF/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.10/themes/black-tie/jquery-ui.css" rel="stylesheet" type="text/css" />`
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link rel="Stylesheet" type="text/css" href="@Url.Content("~/Content/jquery.countdown.css")" />

     <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.0.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.23/jquery-ui.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/additional-methods.js" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/jquery.qtip.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.equalheights.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-timepicker-addon.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.forms.js")" type="text/javascript"></script>

    <script type="text/javascript" src="@Url.Content("~/scripts/jquery.countdown.min.js")"></script>




</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div id="logo">
            </div>
            <div id="login">
               @Html.Partial("_LogOnPartial")
            </div>
        </div>
        <div id="cntwrapper" class="ui-corner-all">
        <div id="nav">
            <div class="content">
                <ul id="main-nav">
                    <li><a href="@Url.Action("Index", "Home")"><span class="main-nav-label">Home</span></a></li>
                    <li><a href="@Url.Action("Index", "MyPredict")"><span class="main-nav-label">My Predict</span></a></li>
                    <li><a href="@Url.Action("HowToPick", "Home")"><span class="main-nav-label">How to Pick</span></a></li>
                    <li><a href="@Url.Action("StandardPicks", "Home")"><span class="main-nav-label">StandardPicks</span></a></li>
                    <li><a href="@Url.Action("About", "Home")"><span class="main-nav-label">About</span></a></li>
                    <li><a href="@Url.Action("Privacy", "Home")"><span class="main-nav-label">Privacy Policy</span></a></li>
                </ul>
            </div>
            <div class="divider">
                &nbsp;</div>
        </div>
        <div id="middle">
            <div class="content">@RenderBody()</div>
        </div>
        </div>
        <div id="footer">&nbsp;
        </div>
    </div>
    <script type="text/javascript">

        $(function () {

            $("input[type='button'], input[type='submit']").button();            

        });
    
    </script>
    </body>
</html>